version: "3"
services:
  db:
    image: "mariadb:latest"
    environment: 
      MARIADB_ROOT_PASSWORD: "58274169"
      MARIADB_DATABASE: "newsmail"
      MARIADB_USER: "root"
    ports: 
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mariadb
  app:
    container_name: newsmail
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db